peer_public = "54.188.24.131"
peer_private = "172.16.0.201"

peer_port = "8000"
peer_file = "10mb.pdf"

pub_request_log_file = "files/pub_request_log.txt"
priv_request_log_file = "files/priv_request_log.txt"

pub_request_err_file = "files/pub_request_err.txt"
priv_request_err_file = "files/priv_request_err.txt"

pub_ping_log_file = "files/pub_ping_log.txt"
priv_ping_log_file = "files/priv_ping_log.txt"

pub_ping_err_file = "files/pub_ping_err.txt"
priv_ping_err_file = "files/priv_ping_err.txt"

ping_count = 5
ping_timeout = 120