peer_public = "54.188.24.131:8000"
peer_private = "172.16.0.201:8000"

peer_file = "10mb.pdf"

pub_request_log_file = "files/pub_request_log.txt"
priv_request_log_file = "files/priv_request_log.txt"

pub_request_err_file = "files/pub_request_err.txt"
priv_request_err_file = "files/priv_request_err.txt"
